name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: "$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending


categories:
  - title: '🚀 New Features'
    collapse-after: 10  
    label: 'feature'
  - title: '🐛 Bug Fixes'
    collapse-after: 10
    labels:
    label: 'bug'
  - title: '🧰 Maintenance'
    collapse-after: 5
    labels:
    label: 'maintenance'
no-changes-template: '- No changes'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$REPO/compare/$PREVIOUS_TAG...$NEW_TAG
