# Delen en bewerken mag maar laat deze eerste regels staan.
# Bron : https://www.huizebruin.nl
# Bron File : https://github.com/huizebruin/s0tool/tree/main/esphome
# © Huizebruin.nl
substitutions:
  name: s0tool-s0-watermeter
  board: esp32-c3-devkitm-1
  gpio_pin: GPIO5

esphome:
  name: ${name}
  name_add_mac_suffix: true
  comment: '${device_description}'
  project:
    name: "lammerink.${name}"
    version: "${project_version}"
  min_version: 2024.6.0
esp8266:
  board:  ${board}
  restore_from_flash: true  

dashboard_import:
  package_import_url: github://lammerink/s0tool/esphome/s0-watermeter.yaml

packages:
  remote_package:
    url: https://github.com/lammerink/s0tool/
    ref: main
    files:
      - esphome/components/basis.yaml
      - esphome/components/s0-watermeter.yaml
      - esphome/components/s0tool-s0-watermeter-update.yml
    refresh: 0d
