name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Read version from YAML file
        id: read_version
        run: |
          yaml_version=$(grep 'project_version:' esphome/components/basis.yaml | awk '{print $2}' | tr -d '"')
          echo "yaml_version=$yaml_version" >> $GITHUB_ENV

      - name: Validate version consistency
        id: validate_version
        run: |
          if [ "${yaml_version}" != "${version}" ]; then
            echo "Tag version (${version}) does not match project_version (${yaml_version}) in YAML file."
            exit 1
          fi

      - uses: release-drafter/release-drafter@v6.0.0
        with:
          tag: ${{ env.version }}
          name: ${{ env.version }}
          version: ${{ env.version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
