name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Get variables
        id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.version.outputs.version }}

      - uses: release-drafter/release-drafter@v6.0.0
        with:
          tag: ${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          version: ${{ steps.version.outputs.version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }